use_frameworks!

platform :ios, '10.0'

target 'ZKQBaseModule_Example' do
  pod 'ZKQBaseModule', :path => '../'

  target 'ZKQBaseModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
